services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    image: cyber-demo-monolith:latest
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    image: cyber-demo-monolith:latest
    entrypoint: ["celery"]
    command: ["-A", "app.celery_app", "worker", "--loglevel=info"]
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
